# Generated by Django 6.0 on 2025-12-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_bot_name', models.CharField(max_length=100)),
                ('second_bot_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AiChat',
                'verbose_name_plural': 'AiChats',
                'ordering': ['-created_at'],
            },
        ),
    ]
